import type { Metadata } from "next";
import "../../../globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import { Resource } from "@/src/app/utils/resource/resourse";
import { Providers } from "@/src/app/components/Providers";
import AlertModal from "@/src/app/components/Toast/Toast";


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  Resource.setUserAgent(navigator.userAgent);

  return (
    <html lang="en">
      <body>
        <Providers>
          <Suspense fallback={<Loading/>}>
            {children}
            <div id="portal-modal"></div>
            <AlertModal />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
