import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './components/providers'
import Header from './home/components/Header/Header'
import Sidebar from './components/sidebar/sidebar'
import AlertModal from './components/toast/toast'
import { Resource } from './utils/resource/resourse'
import { userAgent } from 'next/server'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  Resource.setUserAgent(navigator.userAgent)

  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <div id='portal-modal'></div>
          <AlertModal />
        </Providers>
      </body>
    </html>
  )
}
